package ui

// helpLines is the single source of truth for the ctrl+k help menu.
// Lines starting with "# " are section headers; others are "keys<TAB>description".
func helpLines() []string {
	return []string{
		"# Playback",
		"k  space\tplay or pause (enter too, in the now-playing view)",
		"l  >\tnext track",
		"j  <\tprevious track (restarts the track if more than 3s in)",
		"media keys\tplay/pause, next and previous on the Mac keyboard, Control Centre and AirPods",
		"← / →\tseek 5 seconds back / forward",
		"↑ / ↓  + / -\tvolume up / down (arrows only in the now-playing view)",
		"m\tmute",
		"s\tcycle shuffle: off → tracks → albums",
		"r\tcycle repeat: off → all → one",
		"f\ttoggle crossfade (mix/fade between tracks)",
		"{ / }\tcrossfade length shorter / longer",
		"",
		"# Views",
		"1  2  3\tnow playing / library / queue",
		"tab / shift+tab\tnext / previous view",
		"esc\tback to now playing",
		"ctrl+k  ?\tthis help",
		"ctrl+s\tsave the current settings now (they are also saved on quit)",
		"q  ctrl+c\tquit (settings are saved)",
		"",
		"# Album art & visualizer",
		"a\tswitch between album art and visualizer",
		"A\tart style: blocks (true colour) → ascii → kitty (pixel-perfect in Ghostty/Kitty)",
		"c\tnext ascii character set",
		"v / V\tnext / previous visualizer style",
		"t / T\tnext / previous colour theme ('match' follows the album art)",
		"d\tfind the album cover and the artist photo online and save them (also works on the library selection)",
		"D\treload album art from disk",
		"",
		"# Lyrics",
		"y\tshow / hide the lyrics pane beside the art or visualizer",
		"\t.lrc files and embedded lyrics are used when present; otherwise whisper.cpp",
		"\ttranscribes the song (needs: brew install whisper-cpp ffmpeg). The model is",
		"\tdownloaded on first use and set with whisper_model in the config file.",
		"",
		"# Visualizer tuning (now-playing view)",
		"g / G\tgradient: theme, horizontal, rainbow, spectrum, fire, ice, neon, heat, mono, pastel",
		"i\tfill style: block, shade, braille, ascii, dots, lines, thin",
		"x\tpeak caps on / off",
		"Y\tmirror on / off",
		"z\tstereo split on / off",
		"L\tlogarithmic / linear frequency scale",
		"w / W\tbar width wider / narrower",
		"e / E\tbar gap wider / narrower",
		", / .\tsmoothing less / more",
		"[ / ]\tsensitivity lower / higher",
		"; / '\tfalloff slower / faster",
		"R\treset visualizer options",
		"",
		"# Library",
		"↑ ↓\tmove",
		"→ ←\topen / close artist, album or playlist",
		"b / B\tbrowse by artists → albums → playlists",
		"enter\tplay (a track plays inside its folder)",
		"e\tadd to the end of the queue",
		"E\tplay next",
		"/\tfilter: type to search folders, file names and tag titles",
		"d\tfind covers and the artist photo for the selection (the photo shows behind the list)",
		"o\tjump to the playing track",
		"P\tsave the selected artist, album or playlist as a new playlist",
		"delete\tdelete the selected playlist (asks first)",
		"z\tfold everything",
		"S\trescan the music folder",
		"",
		"# Queue",
		"↑ ↓\tmove",
		"enter\tjump to track",
		"x  delete\tremove track",
		"P\tsave the queue as a playlist (Playlists folder in your music directory)",
		"C\tclear the queue",
		"g\tgo to the playing track",
		"",
		"# Command line",
		"wvfrm\topen the player",
		"wvfrm <words>\tplay the best matching artist, album or track",
		"wvfrm artist|album|track <name>\tplay a specific kind of match",
		"wvfrm shuffle [words]\tshuffle everything (or the matches)",
		"wvfrm all\tplay the whole library in order",
		"wvfrm playlist <name>\tplay a saved playlist (wvfrm playlists lists them)",
		"wvfrm art <album>\tfind and attach cover art without opening the UI",
		"wvfrm path <dir>\tset the music folder",
		"",
		"mouse\tclick tabs, click the progress bar to seek, scroll lists",
	}
}
